name: CI

on:
 push:
   branches:
     - master

jobs:

  ci:
    runs-on: ubuntu-latest

    steps:

      -
        name: Checkout Github Repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      -
        name: Set commit version info
        run: |
          echo "VERSION=sha-$(echo "$GITHUB_SHA" | cut -c1-7)" >> $GITHUB_ENV

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./Dockerfile
          build-args: VERSION=${{ env.VERSION }}
          tags: |
            ${{ secrets.ASTRO_IMAGE_REPOSITORY }}:${{ env.VERSION }}
            ${{ secrets.EC_IMAGE_REPOSITORY }}:${{ env.VERSION }}

      -
        name: Configure EarthChem AWS credentials
        id: ec-creds
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.DEPLOYER_EC_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEPLOYER_EC_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
           
      -
        name: Trigger update to EarthChem staging Fargate cluster
        run: |
          aws cloudformation update-stack \
            --stack-name staging-pid-service-fargate-service \
            --parameters ParameterKey=ImageTag,ParameterValue=${{ env.VERSION}} \
            ParameterKey=ServiceName,UsePreviousValue=true \
            ParameterKey=Environment,UsePreviousValue=true \
            --use-previous-template || true
      -
        name: Configure Astromat AWS credentials
        id: astro-creds
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.DEPLOYER_ASTRO_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEPLOYER_ASTRO_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION}}
           
      -
        name: Trigger update to Astromat staging Fargate cluster
        run: |
          aws cloudformation update-stack \
            --stack-name staging-pid-service-fargate-service \
            --parameters ParameterKey=ImageTag,ParameterValue=${{ env.VERSION}} \
            ParameterKey=ServiceName,UsePreviousValue=true \
            ParameterKey=Environment,UsePreviousValue=true \
            --use-previous-template || true
