name: CI

on: [push]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOYER_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOYER_AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
  IMAGE_REPOSITORY: ${{ secrets.IMAGE_REPOSITORY }}

jobs:

  ci:
    runs-on: ubuntu-latest

    steps:

      -
        name: Checkout Github Repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      -
        name: Set commit version info
        run: |
          echo "VERSION=sha-$(echo "$GITHUB_SHA" | cut -c1-7)" >> $GITHUB_ENV

      -
        name: Set image info
        run: |
          echo "IMAGE=${IMAGE_REPOSITORY}:${VERSION}" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - uses: docker/build-push-action@v2
        id: docker_build
        with:
          push: true
          build-args: VERSION=${{ env.VERSION }}
          tags: ${{ env.IMAGE_REPOSITORY }}:${{ env.VERSION }}

      - name: Trigger update to staging Fargate cluster
        run: |
          aws cloudformation update-stack \
            --stack-name staging-pid-service-fargate-service \
            --parameters ParameterKey=ImageTag,ParameterValue=$VERSION \
            --parameters ParameterKey=ServiceName,UsePreviousValue=true \
            --parameters ParameterKey=Environment,UsePreviousValue=true \
            --use-previous-template || true
